export const LISTEN_TO_HEROES = "LISTEN_TO_HEROES";

export const ADD_HERO = "ADD_HERO";
export const UPDATE_HERO = "UPDATE_HERO";
export const GET_HERO = "GET_HERO";
export const REMOVE_HERO = "REMOVE_HERO";
export const RESET_HEROES = "RESET_HEROES";
export const SEARCH_HERO_FRIENDS = "SEARCH_HERO_FRIENDS";

export const RECEIVE_ADD_HERO = "RECEIVE_ADD_HERO";
export const RECEIVE_UPDATE_HERO = "RECEIVE_UPDATE_HERO";
export const RECEIVE_UPDATE_HERO_TO_LIST = "RECEIVE_UPDATE_HERO_TO_LIST";
export const RECEIVE_GET_HERO = "RECEIVE_GET_HERO";
export const RECEIVE_REMOVE_HERO = "RECEIVE_REMOVE_HERO";
